
DROP TABLE IF EXISTS holidays;

CREATE TABLE IF NOT EXISTS holidays (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(1000),
  local_name VARCHAR(1000),
  date DATE,
  country_code VARCHAR(10),
  fixed BOOLEAN,
  global BOOLEAN
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  text VARCHAR(2000)
);