
DROP TABLE IF EXISTS holidays;

CREATE TABLE IF NOT EXISTS holidays (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(1000),
  local_name VARCHAR(1000),
  date DATE,
  country_code VARCHAR(10),
  fixed BOOLEAN,
  global BOOLEAN
);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  text VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS supported_currencies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(10) NOT NULL,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS convert_rate (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  from_currency_id BIGINT NOT NULL REFERENCES supported_currencies(id),
  to_currency_id BIGINT NOT NULL REFERENCES supported_currencies(id),
  convertedAmount DOUBLE PRECISION NOT NULL
);